# Generated by Django 3.2.8 on 2021-10-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211019_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='topic',
        ),
    ]
